import Head from 'next/head'
import { useState } from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Image from "next/image";
import peacePortrait from "../public/image.png"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      < Head >
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head >

      {/* <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40"> */}
      <main className="bg-white px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          {/* <section> */}
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Sidak Aneja</h2>
            <h3 className="text-2xl py-2 md:text-3xl">Computer Science Student</h3>
            <h3 className="text-xl text-teal-900 md:text-2xl">Aspiring Software Developer</h3>
            <p className="text-md py-4 leading-7 md:text-xl max-w-l mx-auto">
              Interest in back-end development, computer systems, and complex infrastructure systems. I have hands-on experience creating scalable web applications, data pipelines, hardware emulators and embedded systems.
            </p>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 to-teal-100 rounded-full w-80 h-80 overflow-hidden">
            <Image src={peacePortrait} alt="3D image of me" className="mt-5 ml-3" layout="fill" objectFit="cover" />
          </div>
        </section>
      </main>
    </div >
  )
}
