import Head from 'next/head'
import { useState } from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Image from "next/image";
import peacePortrait from "../public/image.png"
import TypingBanner from '../components/Banner.js'

const resumeLink = "https://drive.google.com/file/d/1QS1_ZFq8w_7-m-NGrOaMa5T8CF1sG1nm/view?usp=sharing";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      < Head >
        <title>Sidak Aneja's Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head >

      <main className="bg-white dark:bg-gray-900 px-8 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-8 md:pb-4 md:mb-3 flex justify-between dark:text-gray-200">
            <h1 className="text-xl font-burtons">Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href={resumeLink}>Resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 dark:text-teal-400 font-medium md:text-6xl">Sidak Aneja</h2>
            <TypingBanner />
            <p className="text-md py-4 leading-7 md:text-xl max-w-l mx-auto dark:text-gray-100">
              Passionate about back-end development, computer systems, and complex infrastructure projects. <br />
              I have hands-on experience building scalable web applications, data pipelines, hardware emulators and embedded systems.
            </p>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 to-teal-100 rounded-full w-80 h-80 overflow-hidden">
            <Image src={peacePortrait} alt="3D image of me" className="mt-5 ml-3" layout="fill" objectFit="cover" />
          </div>
        </section>
      </main>
    </div >
  )
}
